// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchCreateRequest = { links: Array<PostNewLink> }

export type BatchDeleteRequest = { codes: Array<string> }

export type BatchFailedItem = { code: string; error: string }

export type BatchResponse = {
  success: Array<string>
  failed: Array<BatchFailedItem>
}

export type BatchUpdateItem = { code: string; payload: PostNewLink }

export type BatchUpdateRequest = { updates: Array<BatchUpdateItem> }

/**
 * 配置历史记录响应
 */
export type ConfigHistoryResponse = {
  id: number
  config_key: string
  old_value: string | null
  new_value: string
  changed_at: string
  changed_by: string | null
}

/**
 * 配置项响应
 */
export type ConfigItemResponse = {
  key: string
  value: string
  /**
   * 值类型
   */
  value_type: ValueType
  requires_restart: boolean
  is_sensitive: boolean
  updated_at: string
}

/**
 * 配置更新请求
 */
export type ConfigUpdateRequest = { value: string }

/**
 * 配置更新响应
 */
export type ConfigUpdateResponse = {
  key: string
  value: string
  requires_restart: boolean
  is_sensitive: boolean
  message: string | null
}

/**
 * 导出查询参数
 */
export type ExportQuery = {
  search: string | null
  created_after: string | null
  created_before: string | null
  only_expired: boolean | null
  only_active: boolean | null
}

export type GetLinksQuery = {
  page: number | null
  page_size: number | null
  created_after: string | null
  created_before: string | null
  only_expired: boolean | null
  only_active: boolean | null
  search: string | null
}

/**
 * 健康检查项容器
 */
export type HealthChecks = { storage: HealthStorageCheck }

/**
 * 健康检查响应
 */
export type HealthResponse = {
  status: string
  timestamp: string
  uptime: number
  checks: HealthChecks
  response_time_ms: number
}

/**
 * 存储后端信息
 */
export type HealthStorageBackend = {
  storage_type: string
  support_click: boolean
}

/**
 * 存储健康检查状态
 */
export type HealthStorageCheck = {
  status: string
  links_count: number | null
  backend: HealthStorageBackend
  error: string | null
}

/**
 * 导入失败项
 */
export type ImportFailedItem = { row: number; code: string; error: string }

/**
 * 导入模式
 */
export type ImportMode = 'skip' | 'overwrite' | 'error'

/**
 * 导入响应
 */
export type ImportResponse = {
  total_rows: number
  success_count: number
  skipped_count: number
  failed_count: number
  failed_items: Array<ImportFailedItem>
}

export type LinkResponse = {
  code: string
  target: string
  created_at: string
  expires_at: string | null
  password: string | null
  click_count: number
}

export type LoginCredentials = { password: string }

export type PaginationInfo = {
  page: number
  page_size: number
  total: number
  total_pages: number
}

export type PostNewLink = {
  code: string | null
  target: string
  expires_at: string | null
  password: string | null
  force: boolean | null
}

/**
 * 统计信息响应
 */
export type StatsResponse = {
  total_links: number
  total_clicks: number
  active_links: number
}

/**
 * 配置值类型枚举
 */
export type ValueType = 'string' | 'int' | 'bool' | 'json'
