// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API 错误码枚举
 *
 * 使用 serde_repr 序列化为数字，ts-rs 自动生成 TypeScript 类型。
 * 按千位分域：
 * - 0: 成功
 * - 1000-1099: 通用错误
 * - 2000-2099: 认证错误
 * - 3000-3099: 链接错误
 * - 4000-4099: 导入导出错误
 * - 5000-5099: 配置错误
 */
export enum ErrorCode { "Success" = 0, "BadRequest" = 1000, "Unauthorized" = 1001, "NotFound" = 1004, "InternalServerError" = 1005, "ServiceUnavailable" = 1030, "AuthFailed" = 2000, "TokenExpired" = 2001, "TokenInvalid" = 2002, "CsrfInvalid" = 2003, "RateLimitExceeded" = 2004, "LinkNotFound" = 3000, "LinkAlreadyExists" = 3001, "LinkInvalidUrl" = 3002, "LinkInvalidExpireTime" = 3003, "LinkPasswordHashError" = 3004, "LinkDatabaseError" = 3005, "LinkEmptyCode" = 3006, "ImportFailed" = 4000, "ExportFailed" = 4001, "InvalidMultipartData" = 4002, "FileReadError" = 4003, "CsvFileMissing" = 4004, "CsvParseError" = 4005, "CsvGenerationError" = 4006, "ConfigNotFound" = 5000, "ConfigUpdateFailed" = 5001, "ConfigReloadFailed" = 5002 }

/**
 * Analytics 查询参数
 */
export type AnalyticsQuery = { 
/**
 * 开始日期 (ISO 8601)
 */
start_date: string | null, 
/**
 * 结束日期 (ISO 8601)
 */
end_date: string | null, 
/**
 * 分组方式
 */
group_by: GroupBy | null, 
/**
 * 返回数量限制
 */
limit: number | null, };

/**
 * 认证成功响应
 */
export type AuthSuccessResponse = { message: string, expires_in: bigint, };

export type BatchCreateRequest = { links: Array<PostNewLink>, };

export type BatchDeleteRequest = { codes: Array<string>, };

export type BatchFailedItem = { code: string, error: string, error_code: number | null, };

export type BatchResponse = { success: Array<string>, failed: Array<BatchFailedItem>, };

export type BatchUpdateItem = { code: string, payload: PostNewLink, };

export type BatchUpdateRequest = { updates: Array<BatchUpdateItem>, };

/**
 * 配置历史记录响应
 */
export type ConfigHistoryResponse = { id: number, config_key: string, old_value: string | null, new_value: string, changed_at: string, changed_by: string | null, };

/**
 * 配置项响应
 */
export type ConfigItemResponse = { key: string, value: string, 
/**
 * 值类型
 */
value_type: ValueType, requires_restart: boolean, is_sensitive: boolean, updated_at: string, };

/**
 * 配置项的 schema 元信息
 */
export type ConfigSchema = { key: string, value_type: ValueType, default_value: string, description: string, category?: string, enum_options?: Array<EnumOption>, requires_restart: boolean, editable: boolean, };

/**
 * 配置更新请求
 */
export type ConfigUpdateRequest = { value: string, };

/**
 * 配置更新响应
 */
export type ConfigUpdateResponse = { key: string, value: string, requires_restart: boolean, is_sensitive: boolean, message: string | null, };

/**
 * 单个 enum 选项
 */
export type EnumOption = { value: string, label: string, label_i18n_key?: string, description?: string, description_i18n_key?: string, };

/**
 * 导出查询参数
 */
export type ExportQuery = { search: string | null, created_after: string | null, created_before: string | null, only_expired: boolean | null, only_active: boolean | null, };

/**
 * 地理位置统计
 */
export type GeoStats = { country: string, city: string | null, count: bigint, };

export type GetLinksQuery = { page: number | null, page_size: number | null, created_after: string | null, created_before: string | null, only_expired: boolean | null, only_active: boolean | null, search: string | null, };

/**
 * 分组方式
 */
export type GroupBy = "hour" | "day" | "week" | "month";

/**
 * 健康检查项容器
 */
export type HealthChecks = { storage: HealthStorageCheck, };

/**
 * 健康检查响应
 */
export type HealthResponse = { status: string, timestamp: string, uptime: number, checks: HealthChecks, response_time_ms: number, };

/**
 * 存储后端信息
 */
export type HealthStorageBackend = { storage_type: string, support_click: boolean, };

/**
 * 存储健康检查状态
 */
export type HealthStorageCheck = { status: string, links_count: number | null, backend: HealthStorageBackend, error: string | null, };

/**
 * HTTP 方法枚举
 */
export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";

/**
 * 导入失败项
 */
export type ImportFailedItem = { row: number, code: string, error: string, error_code: number | null, };

/**
 * 导入模式
 */
export type ImportMode = "skip" | "overwrite" | "error";

/**
 * 导入响应
 */
export type ImportResponse = { total_rows: number, success_count: number, skipped_count: number, failed_count: number, failed_items: Array<ImportFailedItem>, };

/**
 * 单链接分析数据
 */
export type LinkAnalytics = { code: string, total_clicks: bigint, trend: TrendData, top_referrers: Array<ReferrerStats>, geo_distribution: Array<GeoStats>, };

export type LinkResponse = { code: string, target: string, created_at: string, expires_at: string | null, password: string | null, click_count: number, };

export type LoginCredentials = { password: string, };

/**
 * 简单消息响应
 */
export type MessageResponse = { message: string, };

export type PaginationInfo = { page: number, page_size: number, total: number, total_pages: number, };

export type PostNewLink = { code: string | null, target: string, expires_at: string | null, password: string | null, force: boolean | null, };

/**
 * 来源统计
 */
export type ReferrerStats = { referrer: string, count: bigint, percentage: number, };

/**
 * Reload 成功响应
 */
export type ReloadResponse = { message: string, duration_ms: bigint, };

/**
 * Cookie SameSite 策略
 */
export type SameSitePolicy = "Strict" | "Lax" | "None";

/**
 * 统计信息响应
 */
export type StatsResponse = { total_links: number, total_clicks: number, active_links: number, };

/**
 * 热门链接
 */
export type TopLink = { code: string, clicks: bigint, };

/**
 * 点击趋势数据
 */
export type TrendData = { 
/**
 * 时间标签
 */
labels: Array<string>, 
/**
 * 点击数
 */
values: Array<bigint>, };

/**
 * 配置值类型枚举
 *
 * 用于标识配置项在数据库和前端的类型。
 */
export type ValueType = "string" | "int" | "bool" | "json" | "enum" | "stringarray" | "enumarray";
